\"  Copyright 2004,2006,2011 by the Massachusetts Institute of
\"  Technology.  All Rights Reserved.

\"  Permission to use, copy, modify, and distribute this software and
\"  its documentation for any purpose and without fee is hereby
\"  granted, provided that the above copyright notice appear in all
\"  copies and that both that copyright notice and this permission
\"  notice appear in supporting documentation, and that the name of
\"  M.I.T. not be used in advertising or publicity pertaining to
\"  distribution of the software without specific, written prior
\"  permission.  Furthermore if you modify this software you must label
\"  your software as modified software and not distribute it in such a
\"  fashion that it might be confused with the original
\"  M.I.T. software.  M.I.T. makes no representations about the
\"  suitability of this software for any purpose.  It is provided "as
\"  is" without express or implied warranty.

\" $Id$
.TH kredentials 1 2004-08-29 "CSAIL User's Guide"
.
.SH NAME
kredentials \- KDE system tray applet to monitor and update authentication 
tokens
.
.SH DESCRIPTION
Kredentials monitors the state of the user's Kerberos and AFS
authentication tokens.
.
It renews Kerberos tickets every hour up to the maximum renewable
lifetime of the tickets and informs the user when the renewable
lifetime is reached.
.
Each time Kerberos tickets are obtained, aklog(1) is run to obtain new
AFS tokens.
.
.SH OPTIONS
.TP
\-i|--inform
Inform the user via a KDE "passive dialog" each time tickets are renewed.
.TP
\-d|--disable-aklog
Don't run aklog to get new AFS tokens when renewing Kerberos creds.
.SH BUGS
There aren't really any major bugs, but the feature list can and should
be expanded.
.
The command line options should be migrated to GUI-configurable
settings.
.
The ticket renewal interval should be user-configurable.
.
.SH AUTHOR
Kredentials was written by Noah Meyerhans <noahm@csail.mit.edu> for 
The Infrastructure Group at the Massachusetts Institute of Technology
Computer Science and Artificial Intelligence Lab.
.
Please report any problems to noahm@csail.mit.edu
.
